require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'CameraRollExample' do
  # Added for this project (react-native-cameraroll)
  pod 'react-native-cameraroll', :path => "../.."

  # `'../../node_modules/react-native'` added for
  # react-native-cameraroll (our node_modules doesn't live in
  # example/).
  use_react_native!(:path => '../../node_modules/react-native')

  target 'CameraRollExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CameraRollExample-tvOS' do
  # Pods for CameraRollExample-tvOS

  target 'CameraRollExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
